In [ ]:
import numpy as np

# With fixed seed
np.random.seed(10)
matrix_with_seed = np.random.randint(1, 50, size=(3, 3))
print("Matrix with fixed seed:\n", matrix_with_seed)

# Without fixed seed
matrix_without_seed = np.random.randint(1, 50, size=(3, 3))
print("\nMatrix without fixed seed:\n", matrix_without_seed)


Matrix with fixed seed:
 [[10 37 16]
 [ 1 29 26]
 [30 49 30]]

Matrix without fixed seed:
 [[ 9 10  1]
 [43 41 37]
 [17 37 48]]


In [ ]:
import numpy as np

# With fixed seed
np.random.seed(10)
matrix_with_seed = np.random.randint(1, 50, size=(3, 3))
print("Matrix with fixed seed:\n", matrix_with_seed)

# Without fixed seed
matrix_without_seed = np.random.randint(1, 50, size=(3, 3))
print("\nMatrix without fixed seed:\n", matrix_without_seed)


Matrix with fixed seed:
 [[10 37 16]
 [ 1 29 26]
 [30 49 30]]

Matrix without fixed seed:
 [[ 9 10  1]
 [43 41 37]
 [17 37 48]]


In this code, we generate two 3×3 matrices of random integers between 1 and 50. The first matrix is created after setting a fixed seed with `np.random.seed(10)`, which initializes the random number generator to a specific starting point, ensuring that the same sequence of numbers is produced every time the code is run. This makes the output reproducible and predictable.In contrast, the second matrix is generated without resetting the seed, meaning it continues from the current state of the generator. As a result, if we run the code multiple times, the numbers in the second matrix will vary, since the generator's state changes with each call, leading to different outputs.